/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package laboratorio_11;

import javax.swing.JOptionPane;

/**
 *
 * @author ED
 */
public class iniciarSecion extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(iniciarSecion.class.getName());

    /**
     * Creates new form iniciarSecion
     */
    public iniciarSecion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtCorreoInicioSecion = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtContraseñaInicioSecion = new javax.swing.JTextField();
        btnInicioSecion = new javax.swing.JToggleButton();
        btnRegistarse = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel3.setText("Iniciar sesion");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 19, -1, -1));

        txtCorreoInicioSecion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtCorreoInicioSecion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCorreoInicioSecionActionPerformed(evt);
            }
        });
        jPanel3.add(txtCorreoInicioSecion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 215, 30));

        jLabel1.setText("Correo:");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        jLabel2.setText("Contraseña:");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        txtContraseñaInicioSecion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.add(txtContraseñaInicioSecion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 215, 40));

        btnInicioSecion.setBackground(new java.awt.Color(0, 153, 255));
        btnInicioSecion.setForeground(new java.awt.Color(255, 255, 255));
        btnInicioSecion.setActionCommand("Iniciar sesion");
        btnInicioSecion.setAlignmentX(0.9F);
        btnInicioSecion.setAlignmentY(0.9F);
        btnInicioSecion.setBorder(null);
        btnInicioSecion.setLabel("Iniciar sesion");
        btnInicioSecion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioSecionActionPerformed(evt);
            }
        });
        jPanel3.add(btnInicioSecion, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 130, 40));

        btnRegistarse.setForeground(new java.awt.Color(0, 153, 255));
        btnRegistarse.setText("Registrarse");
        btnRegistarse.setBorder(null);
        btnRegistarse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistarseActionPerformed(evt);
            }
        });
        jPanel3.add(btnRegistarse, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, 90, 30));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/image/Captura de pantalla 2025-06-08 203518.png"))); // NOI18N
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, 210, 350));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInicioSecionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioSecionActionPerformed
        // TODO add your handling code here:
        String correo=txtCorreoInicioSecion.getText().trim().toLowerCase();
        String contraseña=txtContraseñaInicioSecion.getText().trim().toLowerCase();
        
       Usuario usuario =Laboratorio_11.usuarios.get(correo);
       //evento a realizar en caso correo y contraseña esten regitrados
       if (usuario != null && usuario.getContraseña().equals(contraseña)) {
           //cerramos la ventana anterior
           this.dispose();
           //invocamos a la pantalla usuario
          // new PantallaUsuario().setVisible(true);
        this.dispose(); // Cierra la ventana de login
       } else {
           //mensaje emergente si el usuario no estaa registrado
           JOptionPane.showMessageDialog(this, "Correo o contraseña incorrectos", "Error", JOptionPane.ERROR_MESSAGE);
       }
    }//GEN-LAST:event_btnInicioSecionActionPerformed

    private void btnRegistarseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistarseActionPerformed
        // TODO add your handling code here:
        //invocamos a  la pantalla de registrar usuario
        this.dispose();
        new registrarUsuario().setVisible(true);
    }//GEN-LAST:event_btnRegistarseActionPerformed

    private void txtCorreoInicioSecionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCorreoInicioSecionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorreoInicioSecionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new iniciarSecion().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnInicioSecion;
    private javax.swing.JButton btnRegistarse;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField txtContraseñaInicioSecion;
    private javax.swing.JTextField txtCorreoInicioSecion;
    // End of variables declaration//GEN-END:variables
}
